name: Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.3'

      - name: Install Composer dependencies
        run: composer install --optimize-autoloader --no-dev --no-progress --no-interaction --prefer-dist

      - name: Install Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '23'

      - name: Install NPM dependencies
        run: npm install

      - name: Sync files to server
        uses: easingthemes/ssh-deploy@v2.1.5
        env:
          SSH_PASSWORD: ${{ secrets.SSH_PASSWORD }}
          SOURCE: '.'
          REMOTE_HOST: ${{ secrets.SSH_HOST }}
          REMOTE_USER: ${{ secrets.SSH_USER }}
          TARGET: ${{ secrets.REMOTE_PATH }}

        - name: Run Remote/Artisan commands
          uses: appleboy/ssh-action@0.1.6
          with:
            host: ${{ secrets.SSH_HOST }}
            username: ${{ secrets.SSH_USER }}
            password: ${{ secrets.SSH_PASSWORD }}
            script: |
              cd ${{ secrets.REMOTE_PATH }}
              php artisan migrate --force
              php artisan optimize